name: TransferUI
main: TransferUI\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.0.2
author: BajanVlogs

commands:
 server:
  description: "This is for transfering servers using CustomUI"
